[platform_profiler]

linux=https://deae-ceme-tools.amd.com/repository/tools/PlatformProfiler/6.2.0/x86/linux/platform-profiler
windows=https://deae-ceme-tools.amd.com/repository/tools/PlatformProfiler/6.2.0/x86/windows/platform-profiler.exe
arm=https://deae-ceme-tools.amd.com/repository/tools/PlatformProfiler/6.2.0/arm64/linux/platform-profiler


; [workload_profiler]

; linux=https://deae-ceme-tools.amd.com/repository/tools/WorkloadProfiler/latest/x86/linux/workload-profiler
; windows=https://deae-ceme-tools.amd.com/repository/tools/WorkloadProfiler/latest/x86/windows/workload-profiler.exe
; arm=https://deae-ceme-tools.amd.com/repository/tools/WorkloadProfiler/latest/arm64/linux/workload-profiler


; [meta_collector]

; linux=https://linux-url
; windows=https://windows-url
; arm=https://arm-url


; [capacity_sizer]

; linux=https://linux-url
; windows=https://windows-url
; arm=https://arm-url
