[platform_profiler]

linux=
; windows=
arm=


[workload_profiler]

linux=
; windows=
arm=


; [meta_collector]

; linux=https://linux-url
; windows=https://windows-url
; arm=https://arm-url


; [capacity_sizer]

; linux=https://linux-url
; windows=https://windows-url
; arm=https://arm-url
