[platform_profiler]

linux=https://dummyjson.com/users
; windows=https://windows-url
; arm=https://arm-url 


[workload_profiler]

linux=https://dummyjson.com/users
; windows=https://windows-url
; arm=https://arm-url


; [meta_collector]

; linux=https://linux-url
; windows=https://windows-url
; arm=https://arm-url


; [capacity_sizer]

; linux=https://linux-url
; windows=https://windows-url
; arm=https://arm-url
