[linux]

username=amd
ip=10.86.24.78
password=amd123

[windows]

username=Administrator
ip=10.86.24.238
password=amd123

[arm]

username=amd
ip=10.216.178.160
password=amd1234!


; [gpu_cluster]

; user=username
; password=password
; ip=192.168.1.13