[linux]

username=ubuntu
ip=18.61.64.108
ssh_key=C:/Users/User/Desktop/code/my-key.pem

; [windows]

; user=username
; password=password
; ip=192.168.1.11

; [arm]

; user=username
; password=password
; ip=192.168.1.12

; [gpu_cluster]

; user=username
; password=password
; ip=192.168.1.13